// DOM-IGNORE-BEGIN
/*
    (c) 2019 Microchip Technology Inc. and its subsidiaries. 
    
    Subject to your compliance with these terms, you may use Microchip software and any 
    derivatives exclusively with Microchip products. It is your responsibility to comply with third party 
    license terms applicable to your use of third party software (including open source software) that 
    may accompany Microchip software.
    
    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER 
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY 
    IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS 
    FOR A PARTICULAR PURPOSE.
    
    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP 
    HAS BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO 
    THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL 
    CLAIMS IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT 
    OF FEES, IF ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS 
    SOFTWARE.
 */
// DOM-IGNORE-END

#include <xc.h>
#include "../utils/delay.h"
#include "adc.h"


void ADC_init(void) {
	MCLK_REGS->MCLK_APBDMASK |= MCLK_APBDMASK_ADC1(1);
    GCLK_REGS->GCLK_PCHCTRL[41] = GCLK_PCHCTRL_GEN_GCLK3 | GCLK_PCHCTRL_CHEN(1);
	
    ADC1_REGS->ADC_CTRLA |= ADC_CTRLA_SWRST(1);
	while(ADC1_REGS->ADC_SYNCBUSY & ADC_SYNCBUSY_SWRST_Msk);
	
	ADC1_REGS->ADC_CTRLA =
		 ADC_CTRLA_ONDEMAND(1)
		| ADC_CTRLA_PRESCALER_DIV2
		| ADC_CTRLA_RUNSTDBY(1);

    ADC1_REGS->ADC_CTRLB =
		  ADC_CTRLB_WINSS(1)
		| ADC_CTRLB_WINMODE_MODE1;
	while(ADC1_REGS->ADC_SYNCBUSY & ADC_SYNCBUSY_CTRLB_Msk);
		
	ADC1_REGS->ADC_INPUTCTRL = 
		  ADC_INPUTCTRL_MUXNEG_GND
		| ADC_INPUTCTRL_MUXPOS_AIN6;
	while(ADC1_REGS->ADC_SYNCBUSY & ADC_SYNCBUSY_INPUTCTRL_Msk);
	
	ADC1_REGS->ADC_REFCTRL = ADC_REFCTRL_REFSEL_INTREF;
	while(ADC1_REGS->ADC_SYNCBUSY & ADC_SYNCBUSY_REFCTRL_Msk);
	
	ADC1_REGS->ADC_WINLT = 1024;
	while(ADC1_REGS->ADC_SYNCBUSY & ADC_SYNCBUSY_WINLT_Msk);
	
	ADC1_REGS->ADC_CALIB =
		  ADC_CALIB_BIASCOMP((*(uint32_t *)SW0_ADDR & (0x7 << 16)) >> 16)
		| ADC_CALIB_BIASR2R((*(uint32_t *)SW0_ADDR & (0x7 << 22)) >> 22)
		| ADC_CALIB_BIASREFBUF((*(uint32_t *)SW0_ADDR & (0x7 << 19)) >> 19);
					
	ADC1_REGS->ADC_EVCTRL = ADC_EVCTRL_STARTEI(1);
		
	ADC1_REGS->ADC_CTRLA |= ADC_CTRLA_ENABLE(1);
	while(ADC1_REGS->ADC_SYNCBUSY & ADC_SYNCBUSY_ENABLE_Msk);

	delay_ms(2);

	while(ADC1_REGS->ADC_STATUS & ADC_STATUS_ADCBUSY_Msk);	
}